name: Build Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 'Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          cache: false
          install: >-
            git
            zip
            mingw-w64-x86_64-go
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gcc-libs

      - name: 'Build'
        run: |
          mkdir prebuilt
          go env
          CGO_CFLAGS="-I$(pwd)/vm_libvix/include" CGO_LDFLAGS="-L$(pwd)/vm_libvix/libs/win64 -lvixAllProducts -lpthread" go build -o prebuilt/openvm-api.exe cmd/server/main.go

      - name: 'Copy RUNTIME'
        run: |
          cp /mingw64/bin/libgcc_s_seh-1.dll prebuilt/
          cp /mingw64/bin/libwinpthread-1.dll prebuilt/
          cp $(pwd)/vm_libvix/libs/win64/vixAllProducts.dll prebuilt/
      
      - name: 'Pack'
        run: |
          cd prebuilt
          zip -r ../openvm-api_prebuilt_win_amd64.zip *

      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
           name: openvm-api_prebuilt_win_amd64
           path: openvm-api_prebuilt_win_amd64.zip
